{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","text":"CommunicatorError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)"},"variants":[{"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"NfinityCloudError.network(cause:)","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO7networkyAC012CommunicatorD00hF0O_tcACmF","modules":[{"name":"PasswordAndNfinityFramework"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","text":"CommunicatorError","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"]]},"abstract":[{"text":"Case represents network error","type":"text"}],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"title":"PasswordAndNfinityFramework","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","type":"topic","role":"collection","url":"\/documentation\/passwordandnfinityframework","kind":"symbol","abstract":[]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","navigatorTitle":[{"kind":"identifier","text":"NfinityCloudError"}],"title":"NfinityCloudError","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfinityCloudError"}],"abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the NfinityÂ Cloud."}],"role":"symbol","type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/network(cause:)":{"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)","kind":"symbol","type":"topic","title":"NfinityCloudError.network(cause:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Case represents network error"}]}}}